# Generated by Django 3.1.7 on 2021-06-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_auto_20210419_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase_postura',
            name='tipo_sistema',
            field=models.CharField(choices=[('A', 'Free range'), ('B', 'Gaiola'), ('C', 'Caipira')], max_length=1),
        ),
        migrations.AlterField(
            model_name='movimento_diario_postura',
            name='mortalidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movimento_diario_postura',
            name='primeira_coleta',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movimento_diario_postura',
            name='segunda_coleta',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
