# Generated by Django 3.1.7 on 2021-07-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0003_auto_20210616_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento_diario_postura',
            name='ovos_quebrados',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
