# Generated by Django 3.1.7 on 2021-04-13 12:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('doses', models.CharField(choices=[('A', 'X'), ('B', 'Y'), ('C', 'Z')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tempo_vacinacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via_administracao', models.CharField(choices=[('A', 'X'), ('B', 'Y'), ('C', 'Z')], max_length=100)),
                ('periodo_administracao', models.CharField(max_length=100)),
                ('fk_vacina', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vacina.vacina')),
            ],
        ),
        migrations.CreateModel(
            name='Aplicacao_vacina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('observacoes', models.CharField(max_length=400)),
                ('fk_vacina', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vacina.vacina')),
            ],
        ),
    ]
