# Generated by Django 3.1.7 on 2021-04-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacina', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacao_vacina',
            options={'ordering': ('lote', 'vacina')},
        ),
        migrations.AlterModelOptions(
            name='tempo_vacinacao',
            options={'ordering': ('vacina', 'periodo_administracao')},
        ),
        migrations.AlterModelOptions(
            name='vacina',
            options={'ordering': ('tipo',)},
        ),
        migrations.RenameField(
            model_name='aplicacao_vacina',
            old_name='fk_lote',
            new_name='lote',
        ),
        migrations.RenameField(
            model_name='aplicacao_vacina',
            old_name='fk_vacina',
            new_name='vacina',
        ),
        migrations.RenameField(
            model_name='tempo_vacinacao',
            old_name='fk_vacina',
            new_name='vacina',
        ),
        migrations.AlterField(
            model_name='aplicacao_vacina',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aplicacao_vacina',
            name='observacoes',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='tempo_vacinacao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tempo_vacinacao',
            name='via_administracao',
            field=models.CharField(choices=[('A', 'Oral'), ('B', 'Y'), ('C', 'Z')], max_length=1),
        ),
        migrations.AlterField(
            model_name='vacina',
            name='doses',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vacina',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
