# Generated by Django 3.2 on 2021-04-13 18:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('aptidao', models.CharField(choices=[('A', 'Corte'), ('B', 'Postura')], default='B', max_length=1)),
                ('data_chegada', models.DateField(default=datetime.date.today)),
                ('localidade', models.CharField(max_length=200)),
                ('quantidade_aves_chegada', models.PositiveIntegerField()),
                ('quantidade_aves_final', models.PositiveIntegerField(blank=True, null=True)),
                ('raca', models.CharField(choices=[('A', 'Raça 1'), ('B', 'Raça 2'), ('C', 'Raça 3'), ('D', 'Raça 4')], max_length=1)),
                ('status', models.CharField(choices=[('A', 'Isolamento'), ('B', 'Liberados'), ('C', 'Finalizado')], default='A', max_length=1)),
            ],
            options={
                'ordering': ('status', 'data_chegada'),
            },
        ),
        migrations.CreateModel(
            name='Registro_diario_lote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('mortalidade', models.PositiveIntegerField()),
                ('data', models.DateField(default=datetime.date.today)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lote.lote')),
            ],
            options={
                'ordering': ('lote', '-data'),
            },
        ),
    ]
