# Generated by Django 3.1.7 on 2021-02-19 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidade', models.CharField(max_length=200)),
                ('data_chegada', models.DateField(default=datetime.date.today)),
                ('quantidade_inicial', models.IntegerField()),
                ('quantidade_final', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'Isolamento'), ('B', 'Liberados'), ('C', 'Finalizado')], default='A', max_length=1)),
            ],
            options={
                'ordering': ('status', 'data_chegada'),
            },
        ),
    ]
