# Generated by Django 3.1.7 on 2021-02-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0002_auto_20210219_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'ordering': ('status', '-data_chegada')},
        ),
    ]
