# Generated by Django 3.1.7 on 2021-04-08 14:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0003_auto_20210219_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'ordering': ('status', 'data_chegada')},
        ),
        migrations.RemoveField(
            model_name='lote',
            name='quantidade_final',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='quantidade_inicial',
        ),
        migrations.AddField(
            model_name='lote',
            name='aptidao',
            field=models.CharField(choices=[('A', 'Corte'), ('B', 'Postura')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='lote',
            name='codigo',
            field=models.CharField(default='xxx', max_length=50),
        ),
        migrations.AddField(
            model_name='lote',
            name='quantidade_aves_chegada',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='quantidade_aves_final',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='raca',
            field=models.CharField(choices=[('A', 'Raça 1'), ('B', 'Raça 2'), ('C', 'Raça 3'), ('D', 'Raça 4')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Registro_diario_lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=3, max_digits=10)),
                ('mortalidade', models.PositiveIntegerField()),
                ('data', models.DateField(default=datetime.date.today)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lote.lote')),
            ],
            options={
                'ordering': ('lote', '-data'),
            },
        ),
    ]
