# Generated by Django 3.1.7 on 2021-04-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0004_auto_20210408_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='codigo',
            field=models.CharField(default='xxx', max_length=50),
        ),
    ]
