# Generated by Django 3.1.7 on 2021-04-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0005_auto_20210408_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='quantidade_aves_chegada',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lote',
            name='raca',
            field=models.CharField(choices=[('A', 'Raça 1'), ('B', 'Raça 2'), ('C', 'Raça 3'), ('D', 'Raça 4')], max_length=1),
        ),
    ]
