# Generated by Django 3.1.7 on 2021-04-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0006_auto_20210408_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='quantidade_aves_final',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
