# Generated by Django 3.1.7 on 2021-04-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0007_auto_20210408_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_diario_lote',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
