# Generated by Django 3.1.7 on 2021-06-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0002_auto_20210419_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro_diario_lote',
            options={'ordering': ('-lote', '-data')},
        ),
        migrations.AlterField(
            model_name='registro_diario_lote',
            name='mortalidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
