# Generated by Django 3.2 on 2021-04-13 18:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase_postura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_sistema', models.CharField(choices=[('A', 'X'), ('B', 'Y'), ('C', 'Z')], max_length=100)),
                ('data_chegada', models.DateField(default=datetime.date.today)),
                ('quantidade_aves_chegada', models.PositiveIntegerField()),
                ('quantidade_aves_final', models.PositiveIntegerField(blank=True, null=True)),
                ('observacoes', models.CharField(max_length=400)),
                ('fk_lote', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lote.lote')),
            ],
            options={
                'ordering': ('data_chegada', 'quantidade_aves_final'),
            },
        ),
        migrations.CreateModel(
            name='Movimento_diario_postura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(default=datetime.date.today)),
                ('mortalidade', models.PositiveIntegerField()),
                ('primeira_coleta', models.PositiveIntegerField()),
                ('segunda_coleta', models.PositiveIntegerField()),
                ('ovos_quebrados', models.PositiveIntegerField()),
                ('percentual_postura', models.PositiveIntegerField()),
                ('fk_fase_postura', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='producao.fase_postura')),
            ],
            options={
                'ordering': ('data', 'mortalidade'),
            },
        ),
    ]
