# Generated by Django 3.1.7 on 2021-04-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fase_postura',
            options={'ordering': ('status', 'tipo_sistema')},
        ),
        migrations.AlterModelOptions(
            name='movimento_diario_postura',
            options={'ordering': ('fase_postura', 'data')},
        ),
        migrations.RenameField(
            model_name='fase_postura',
            old_name='fk_lote',
            new_name='lote',
        ),
        migrations.RenameField(
            model_name='movimento_diario_postura',
            old_name='fk_fase_postura',
            new_name='fase_postura',
        ),
        migrations.AddField(
            model_name='fase_postura',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('B', 'Inativo')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='fase_postura',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fase_postura',
            name='observacoes',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='fase_postura',
            name='tipo_sistema',
            field=models.CharField(choices=[('A', 'Free range'), ('B', '...'), ('C', '...')], max_length=1),
        ),
        migrations.AlterField(
            model_name='movimento_diario_postura',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movimento_diario_postura',
            name='percentual_postura',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
