# Generated by Django 3.1.7 on 2021-08-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0004_auto_20210721_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase_postura',
            name='media_postura_diaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
