# Generated by Django 3.2 on 2021-04-13 18:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('doses', models.CharField(choices=[('A', 'X'), ('B', 'Y'), ('C', 'Z')], max_length=50)),
            ],
            options={
                'ordering': ('tipo', 'doses'),
            },
        ),
        migrations.CreateModel(
            name='Tempo_vacinacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('via_administracao', models.CharField(choices=[('A', 'X'), ('B', 'Y'), ('C', 'Z')], max_length=100)),
                ('periodo_administracao', models.CharField(max_length=100)),
                ('fk_vacina', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vacina.vacina')),
            ],
            options={
                'ordering': ('fk_vacina', 'via_administracao'),
            },
        ),
        migrations.CreateModel(
            name='Aplicacao_vacina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(default=datetime.date.today)),
                ('observacoes', models.CharField(max_length=400)),
                ('fk_lote', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lote.lote')),
                ('fk_vacina', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vacina.vacina')),
            ],
            options={
                'ordering': ('data', 'fk_vacina'),
            },
        ),
    ]
